import { Protocol, ProtocolStatus } from '../types/protocol';

export const mockProtocols: Protocol[] = [
  {
    id: 'protocol-1',
    title: 'CRISPR-Cas9 Gene Editing in HEK293 Cells',
    description: 'Complete protocol for CRISPR-Cas9 mediated gene knockout in human embryonic kidney cells',
    status: ProtocolStatus.COMPLETED,
    query: 'CRISPR Cas9 gene editing protocol HEK293',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    generatedBy: 'agent-3',
    papers: [
      {
        pmid: '28869965',
        pmcid: 'PMC5572543',
        title: 'CRISPR-Cas9 gene editing in human cells',
        authors: ['Smith J', 'Johnson A', 'Williams B'],
        journal: 'Nature Methods',
        year: 2017,
        relevanceScore: 0.95,
        citedSections: ['Introduction', 'Step 3', 'Step 5'],
      },
      {
        pmid: '29456789',
        pmcid: 'PMC5698234',
        title: 'Optimizing CRISPR delivery in mammalian cells',
        authors: ['Brown C', 'Davis M'],
        journal: 'Cell Reports',
        year: 2018,
        relevanceScore: 0.88,
        citedSections: ['Step 2', 'Step 4'],
      },
    ],
    content: {
      materials: [
        'HEK293 cells',
        'CRISPR-Cas9 plasmid (px458 or similar)',
        'sgRNA targeting your gene of interest',
        'Lipofectamine 3000',
        "DMEM + 10% FBS + 1% Pen/Strep",
        '6-well tissue culture plates',
        'PBS (sterile)',
        'Trypsin-EDTA',
      ],
      steps: [
        {
          stepNumber: 1,
          title: 'Cell Culture Preparation',
          description: 'Seed HEK293 cells at 2x10^5 cells per well in 6-well plates. Incubate overnight at 37°C, 5% CO2 to reach 70-80% confluency.',
          duration: '24 hours',
          materials: ['HEK293 cells', '6-well plates', 'DMEM + 10% FBS'],
          references: ['28869965'],
        },
        {
          stepNumber: 2,
          title: 'Transfection Complex Preparation',
          description: 'Prepare transfection complex by mixing 2.5μg CRISPR plasmid with 5μL Lipofectamine 3000 in 250μL Opti-MEM. Incubate for 15 minutes at room temperature.',
          duration: '20 minutes',
          materials: ['CRISPR-Cas9 plasmid', 'Lipofectamine 3000', 'Opti-MEM'],
          warnings: ['Ensure plasmid DNA is endotoxin-free'],
          references: ['28869965', '29456789'],
        },
        {
          stepNumber: 3,
          title: 'Cell Transfection',
          description: 'Add transfection complex dropwise to cells. Gently rock plate to distribute. Incubate for 48 hours at 37°C, 5% CO2.',
          duration: '48 hours',
          materials: [],
          warnings: ['Do not disturb cells for first 6 hours after transfection'],
          references: ['28869965'],
        },
        {
          stepNumber: 4,
          title: 'Selection and Expansion',
          description: 'If plasmid contains selection marker, add appropriate antibiotic. For GFP+ cells, perform FACS sorting. Expand selected clones.',
          duration: '7-14 days',
          materials: ['Selection antibiotic or FACS'],
          references: ['29456789'],
        },
        {
          stepNumber: 5,
          title: 'Validation',
          description: 'Extract genomic DNA and perform PCR amplification of target region. Confirm editing by Sanger sequencing or T7 endonuclease assay.',
          duration: '2-3 days',
          materials: ['DNA extraction kit', 'PCR primers', 'Sequencing primers'],
          references: ['28869965'],
        },
      ],
      notes: [
        'Transfection efficiency in HEK293 cells typically ranges from 60-80%',
        'Design sgRNAs with high specificity scores to minimize off-target effects',
        'Include a non-targeting control sgRNA in parallel experiments',
        'For stable cell lines, perform single-cell cloning after selection',
      ],
      estimatedTime: '2-3 weeks',
      difficulty: 'intermediate',
    },
    metadata: {
      version: 1,
      papersAnalyzed: 2,
      confidenceScore: 0.92,
      tags: ['CRISPR', 'gene-editing', 'HEK293', 'transfection'],
    },
  },
  {
    id: 'protocol-2',
    title: 'Western Blot for Protein Expression Analysis',
    description: 'Standard Western blot protocol for detecting and quantifying protein expression',
    status: ProtocolStatus.COMPLETED,
    query: 'Western blot protein detection protocol',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    generatedBy: 'agent-3',
    papers: [
      {
        pmid: '25123456',
        pmcid: 'PMC4567890',
        title: 'Western blotting techniques for protein analysis',
        authors: ['Taylor R', 'Anderson K'],
        journal: 'Methods in Molecular Biology',
        year: 2016,
        relevanceScore: 0.93,
        citedSections: ['Step 1', 'Step 2', 'Step 3'],
      },
    ],
    content: {
      materials: [
        'Protein samples',
        'RIPA lysis buffer with protease inhibitors',
        'BCA protein assay kit',
        'SDS-PAGE running buffer',
        'Transfer buffer (Tris-glycine with 20% methanol)',
        'PVDF or nitrocellulose membrane',
        'Blocking buffer (5% milk in TBST)',
        'Primary antibody',
        'HRP-conjugated secondary antibody',
        'ECL detection reagent',
      ],
      steps: [
        {
          stepNumber: 1,
          title: 'Protein Extraction and Quantification',
          description: 'Lyse cells in RIPA buffer with protease inhibitors. Centrifuge at 14,000g for 15 min at 4°C. Quantify protein using BCA assay.',
          duration: '1 hour',
          materials: ['RIPA buffer', 'BCA kit'],
          warnings: ['Keep samples on ice at all times'],
          references: ['25123456'],
        },
        {
          stepNumber: 2,
          title: 'SDS-PAGE',
          description: 'Load 20-30μg protein per lane. Run gel at 100V until dye front reaches bottom.',
          duration: '1-2 hours',
          materials: ['Precast gel or gel casting materials'],
          references: ['25123456'],
        },
        {
          stepNumber: 3,
          title: 'Transfer to Membrane',
          description: 'Transfer proteins to PVDF membrane at 100V for 1 hour at 4°C. Confirm transfer with Ponceau S staining.',
          duration: '1.5 hours',
          materials: ['PVDF membrane', 'Transfer buffer'],
          warnings: ['Pre-activate PVDF in methanol'],
          references: ['25123456'],
        },
        {
          stepNumber: 4,
          title: 'Blocking and Antibody Incubation',
          description: 'Block membrane in 5% milk/TBST for 1 hour. Incubate with primary antibody overnight at 4°C. Wash 3x with TBST. Incubate with secondary antibody for 1 hour at RT.',
          duration: '14-16 hours total',
          materials: ['Blocking buffer', 'Primary antibody', 'Secondary antibody'],
          references: ['25123456'],
        },
        {
          stepNumber: 5,
          title: 'Detection',
          description: 'Apply ECL reagent and image using chemiluminescence imager. Quantify bands using ImageJ or similar software.',
          duration: '30 minutes',
          materials: ['ECL reagent', 'Imaging system'],
          references: ['25123456'],
        },
      ],
      notes: [
        'Always include a loading control (β-actin, GAPDH, etc.)',
        'Optimize antibody dilutions empirically',
        'Use fresh transfer buffer for best results',
        'Store blocked membranes at 4°C in TBST for up to 1 week',
      ],
      estimatedTime: '2 days',
      difficulty: 'beginner',
    },
    metadata: {
      version: 1,
      papersAnalyzed: 1,
      confidenceScore: 0.89,
      tags: ['western-blot', 'protein-analysis', 'immunoblotting'],
    },
  },
  {
    id: 'protocol-3',
    title: 'PCR Amplification of DNA Fragments',
    description: 'Standard PCR protocol for amplifying specific DNA sequences',
    status: ProtocolStatus.COMPLETED,
    query: 'PCR DNA amplification protocol',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 47).toISOString(),
    generatedBy: 'agent-3',
    papers: [],
    content: {
      materials: ['Template DNA', 'Forward and reverse primers', 'dNTP mix', 'DNA polymerase', 'PCR buffer', 'MgCl2'],
      steps: [
        {
          stepNumber: 1,
          title: 'Prepare PCR Mix',
          description: 'Combine template DNA, primers, dNTPs, polymerase, and buffer in PCR tube.',
          duration: '15 minutes',
          materials: ['All PCR reagents'],
          references: [],
        },
      ],
      notes: ['Optimize annealing temperature based on primer Tm'],
      estimatedTime: '3 hours',
      difficulty: 'beginner',
    },
    metadata: {
      version: 1,
      papersAnalyzed: 0,
      confidenceScore: 0.75,
      tags: ['PCR', 'DNA-amplification'],
    },
  },
  {
    id: 'protocol-4',
    title: 'Mammalian Cell Culture: Passaging and Maintenance',
    description: 'Routine protocols for maintaining adherent mammalian cell lines',
    status: ProtocolStatus.IN_PROGRESS,
    query: 'mammalian cell culture passaging protocol',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    generatedBy: 'agent-3',
    papers: [],
    metadata: {
      version: 1,
      papersAnalyzed: 3,
      tags: ['cell-culture', 'passaging', 'maintenance'],
    },
  },
  {
    id: 'protocol-5',
    title: 'Flow Cytometry Analysis for Cell Surface Markers',
    description: 'Protocol for staining and analyzing cell surface proteins by flow cytometry',
    status: ProtocolStatus.FAILED,
    query: 'flow cytometry cell surface marker staining',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    generatedBy: 'agent-3',
    papers: [],
    metadata: {
      version: 1,
      papersAnalyzed: 0,
      tags: ['flow-cytometry', 'immunostaining'],
    },
  },
  {
    id: 'protocol-6',
    title: 'RNA Extraction from Cultured Cells',
    description: 'Total RNA isolation protocol using TRIzol method',
    status: ProtocolStatus.COMPLETED,
    query: 'RNA extraction protocol TRIzol',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 71).toISOString(),
    generatedBy: 'agent-3',
    papers: [],
    content: {
      materials: ['TRIzol reagent', 'Chloroform', 'Isopropanol', 'Ethanol 75%', 'RNase-free water'],
      steps: [
        {
          stepNumber: 1,
          title: 'Cell Lysis',
          description: 'Add 1mL TRIzol per 10cm dish. Incubate 5 minutes at RT.',
          duration: '5 minutes',
          materials: ['TRIzol'],
          warnings: ['Work in fume hood'],
          references: [],
        },
      ],
      notes: ['Use RNase-free tubes and tips'],
      estimatedTime: '2 hours',
      difficulty: 'beginner',
    },
    metadata: {
      version: 1,
      papersAnalyzed: 0,
      confidenceScore: 0.82,
      tags: ['RNA', 'extraction', 'TRIzol'],
    },
  },
  {
    id: 'protocol-7',
    title: 'Immunofluorescence Staining of Fixed Cells',
    description: 'Protocol for visualizing proteins in fixed cells using fluorescent antibodies',
    status: ProtocolStatus.COMPLETED,
    query: 'immunofluorescence microscopy protocol',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 119).toISOString(),
    generatedBy: 'agent-3',
    papers: [],
    content: {
      materials: ['Coverslips', '4% PFA', 'PBS', 'Triton X-100', 'Blocking buffer', 'Primary antibody', 'Fluorescent secondary antibody', 'DAPI'],
      steps: [
        {
          stepNumber: 1,
          title: 'Fixation',
          description: 'Fix cells with 4% PFA for 15 minutes at RT. Wash 3x with PBS.',
          duration: '20 minutes',
          materials: ['PFA', 'PBS'],
          warnings: ['PFA is toxic - use in fume hood'],
          references: [],
        },
      ],
      notes: ['Mount with anti-fade mounting medium'],
      estimatedTime: '6 hours',
      difficulty: 'intermediate',
    },
    metadata: {
      version: 1,
      papersAnalyzed: 0,
      confidenceScore: 0.86,
      tags: ['immunofluorescence', 'microscopy', 'staining'],
    },
  },
  {
    id: 'protocol-8',
    title: 'Lentiviral Transduction for Stable Gene Expression',
    description: 'Protocol for generating stable cell lines using lentiviral vectors',
    status: ProtocolStatus.VALIDATING,
    query: 'lentivirus transduction stable cell line',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    generatedBy: 'agent-4',
    papers: [],
    metadata: {
      version: 1,
      papersAnalyzed: 5,
      tags: ['lentivirus', 'transduction', 'stable-expression'],
    },
  },
  {
    id: 'protocol-9',
    title: 'ELISA for Cytokine Detection',
    description: 'Enzyme-linked immunosorbent assay for quantifying cytokines in cell culture supernatants',
    status: ProtocolStatus.COMPLETED,
    query: 'ELISA cytokine detection protocol',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 95).toISOString(),
    generatedBy: 'agent-3',
    papers: [],
    content: {
      materials: ['ELISA kit', '96-well plate', 'Plate reader', 'Wash buffer', 'Standards'],
      steps: [
        {
          stepNumber: 1,
          title: 'Plate Coating',
          description: 'Add capture antibody to wells. Incubate overnight at 4°C.',
          duration: '12 hours',
          materials: ['Capture antibody'],
          references: [],
        },
      ],
      notes: ['Follow kit instructions for optimal results'],
      estimatedTime: '1 day',
      difficulty: 'beginner',
    },
    metadata: {
      version: 1,
      papersAnalyzed: 0,
      confidenceScore: 0.79,
      tags: ['ELISA', 'cytokine', 'immunoassay'],
    },
  },
  {
    id: 'protocol-10',
    title: 'Chromatin Immunoprecipitation (ChIP) Assay',
    description: 'Protocol for studying protein-DNA interactions in living cells',
    status: ProtocolStatus.PENDING,
    query: 'ChIP assay protocol chromatin immunoprecipitation',
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    generatedBy: 'agent-3',
    papers: [],
    metadata: {
      version: 1,
      papersAnalyzed: 0,
      tags: ['ChIP', 'chromatin', 'epigenetics'],
    },
  },
];
