import { User, UserStats } from '../types/user';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@bioprotocol.org',
    name: 'Dr. Sarah Johnson',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    lastLogin: new Date('2025-02-02T10:30:00'),
    protocolsGenerated: 45,
    papersAccessed: 234,
  },
  {
    id: 'user-2',
    email: 'researcher1@bioprotocol.org',
    name: 'Dr. Michael Chen',
    role: 'researcher',
    status: 'active',
    createdAt: new Date('2024-03-20'),
    lastLogin: new Date('2025-02-01T15:45:00'),
    protocolsGenerated: 28,
    papersAccessed: 156,
  },
  {
    id: 'user-3',
    email: 'researcher2@bioprotocol.org',
    name: 'Dr. Emily Rodriguez',
    role: 'researcher',
    status: 'active',
    createdAt: new Date('2024-04-10'),
    lastLogin: new Date('2025-02-02T09:20:00'),
    protocolsGenerated: 32,
    papersAccessed: 189,
  },
  {
    id: 'user-4',
    email: 'viewer1@bioprotocol.org',
    name: 'John Smith',
    role: 'viewer',
    status: 'active',
    createdAt: new Date('2024-06-05'),
    lastLogin: new Date('2025-01-30T14:10:00'),
    protocolsGenerated: 0,
    papersAccessed: 45,
  },
  {
    id: 'user-5',
    email: 'researcher3@bioprotocol.org',
    name: 'Dr. Lisa Wang',
    role: 'researcher',
    status: 'inactive',
    createdAt: new Date('2024-02-28'),
    lastLogin: new Date('2024-12-20T11:30:00'),
    protocolsGenerated: 15,
    papersAccessed: 87,
  },
  {
    id: 'user-6',
    email: 'researcher4@bioprotocol.org',
    name: 'Dr. James Wilson',
    role: 'researcher',
    status: 'suspended',
    createdAt: new Date('2024-05-12'),
    lastLogin: new Date('2024-11-15T16:20:00'),
    protocolsGenerated: 8,
    papersAccessed: 34,
  },
  {
    id: 'user-7',
    email: 'admin2@bioprotocol.org',
    name: 'Dr. Maria Garcia',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-01-20'),
    lastLogin: new Date('2025-02-02T08:15:00'),
    protocolsGenerated: 38,
    papersAccessed: 201,
  },
  {
    id: 'user-8',
    email: 'viewer2@bioprotocol.org',
    name: 'Alice Brown',
    role: 'viewer',
    status: 'active',
    createdAt: new Date('2024-07-22'),
    lastLogin: new Date('2025-02-01T13:40:00'),
    protocolsGenerated: 0,
    papersAccessed: 23,
  },
];

export const getUserStats = (): UserStats => {
  return {
    totalUsers: mockUsers.length,
    activeUsers: mockUsers.filter((u) => u.status === 'active').length,
    adminUsers: mockUsers.filter((u) => u.role === 'admin').length,
    researcherUsers: mockUsers.filter((u) => u.role === 'researcher').length,
    viewerUsers: mockUsers.filter((u) => u.role === 'viewer').length,
  };
};
