"""add_is_deleted_to_search_history_and_analysis_results

Revision ID: 044db88c5e82
Revises: 33318fedbd63
Create Date: 2026-04-02 16:46:32.225823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044db88c5e82'
down_revision: Union[str, Sequence[str], None] = '33318fedbd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('search_history', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'is_deleted')
    op.drop_column('analysis_results', 'is_deleted')
    # ### end Alembic commands ###
