"""add paper_summary review formulas to analysis_results

Revision ID: 33318fedbd63
Revises: 0001
Create Date: 2026-03-30 12:28:05.295326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33318fedbd63'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('paper_summary', sa.Text(), nullable=False, server_default=''))
    op.add_column('analysis_results', sa.Column('paper_review', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('analysis_results', sa.Column('key_formulas', sa.JSON(), nullable=False, server_default='[]'))
    op.drop_constraint(op.f('papers_arxiv_id_key'), 'papers', type_='unique')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=False)
    op.create_unique_constraint(op.f('papers_arxiv_id_key'), 'papers', ['arxiv_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('analysis_results', 'key_formulas')
    op.drop_column('analysis_results', 'paper_review')
    op.drop_column('analysis_results', 'paper_summary')
    # ### end Alembic commands ###
